name: CI Pipeline

on:
  push:
  pull_request:

jobs:

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build App
        run: |
          echo "Building application"
          echo "Done"

  run-unit-test:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare testing data
        run: echo "Prepare testing data"

      - name: Run unit test
        run: echo "Run unit test"

      - name: Clean up temporary data
        run: echo "Clean up temporary data"

  run-lint:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linter
        run: echo "Running Linter"

  build-image:
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - name: Build image
        run: echo "Building images"

  push-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Push image
        run: echo "Pushing images"

  deploy:
    runs-on: ubuntu-latest
    needs: push-image
    steps:
      - name: Deploy staging server
        run: echo "Deploy staging server"
